 
.SUFFIXES: .java .class

#=========================================================================
# Unix version
#=========================================================================
#CLASSES=../../../classes
#CLASSESDIR=$(CLASSES)/kawa/standard/
#JAVAC=javac -classpath $(CLASSES):$$CLASSPATH
# 
#$(CLASSESDIR)%.class: %.java
#	$(JAVAC) -d $(CLASSES) $<
 
#=========================================================================
# WIN32 version (NMAKE)
#=========================================================================
CLASSES=..\..\..\classes
CLASSESDIR=$(CLASSES)\kawa\standard\ 
JAVAC=javac -classpath $(CLASSES);%CLASSPATH%
.java{$(CLASSESDIR)}.class:
	$(JAVAC) -d $(CLASSES) $(*F).java
 

OBJ=\
$(CLASSESDIR)set_b.class \
$(CLASSESDIR)not.class \
$(CLASSESDIR)boolean_p.class \
$(CLASSESDIR)eqv_p.class \
$(CLASSESDIR)eq_p.class \
$(CLASSESDIR)equal_p.class \
$(CLASSESDIR)pair_p.class \
$(CLASSESDIR)cons.class \
$(CLASSESDIR)car.class \
$(CLASSESDIR)cdr.class \
$(CLASSESDIR)setcar_b.class \
$(CLASSESDIR)setcdr_b.class \
$(CLASSESDIR)caar.class \
$(CLASSESDIR)cadr.class \
$(CLASSESDIR)cdar.class \
$(CLASSESDIR)cddr.class \
$(CLASSESDIR)caaar.class \
$(CLASSESDIR)caadr.class \
$(CLASSESDIR)cadar.class \
$(CLASSESDIR)caddr.class \
$(CLASSESDIR)cdaar.class \
$(CLASSESDIR)cdadr.class \
$(CLASSESDIR)cddar.class \
$(CLASSESDIR)cdddr.class \
$(CLASSESDIR)caaaar.class \
$(CLASSESDIR)caadar.class \
$(CLASSESDIR)caaadr.class \
$(CLASSESDIR)caaddr.class \
$(CLASSESDIR)cadaar.class \
$(CLASSESDIR)cadadr.class \
$(CLASSESDIR)caddar.class \
$(CLASSESDIR)cadddr.class \
$(CLASSESDIR)cdaaar.class \
$(CLASSESDIR)cdaadr.class \
$(CLASSESDIR)cdadar.class \
$(CLASSESDIR)cdaddr.class \
$(CLASSESDIR)cddaar.class \
$(CLASSESDIR)cddadr.class \
$(CLASSESDIR)cdddar.class \
$(CLASSESDIR)cddddr.class \
$(CLASSESDIR)null_p.class \
$(CLASSESDIR)list_p.class \
$(CLASSESDIR)list.class \
$(CLASSESDIR)length.class \
$(CLASSESDIR)append.class \
$(CLASSESDIR)list_tail.class \
$(CLASSESDIR)list_ref.class \
$(CLASSESDIR)mem.class \
$(CLASSESDIR)ass.class \
$(CLASSESDIR)symbol_p.class \
$(CLASSESDIR)symbol2string.class \
$(CLASSESDIR)string2symbol.class \
$(CLASSESDIR)number_p.class \
$(CLASSESDIR)real_p.class \
$(CLASSESDIR)integer_p.class \
$(CLASSESDIR)zero_p.class \
$(CLASSESDIR)positive_p.class \
$(CLASSESDIR)negative_p.class \
$(CLASSESDIR)equal_oper.class \
$(CLASSESDIR)less_oper.class \
$(CLASSESDIR)lessequal_oper.class \
$(CLASSESDIR)greater_oper.class \
$(CLASSESDIR)greaterequal_oper.class \
$(CLASSESDIR)plus_oper.class \
$(CLASSESDIR)minus_oper.class \
$(CLASSESDIR)multiply_oper.class \
$(CLASSESDIR)divide_oper.class \
$(CLASSESDIR)abs.class \
$(CLASSESDIR)char_p.class \
$(CLASSESDIR)char_equal_p.class \
$(CLASSESDIR)char_less_p.class \
$(CLASSESDIR)char_less_equal_p.class \
$(CLASSESDIR)char_greater_p.class \
$(CLASSESDIR)char_greater_equal_p.class \
$(CLASSESDIR)string_p.class \
$(CLASSESDIR)make_string.class \
$(CLASSESDIR)string.class \
$(CLASSESDIR)string_length.class \
$(CLASSESDIR)string_ref.class \
$(CLASSESDIR)string_set_b.class \
$(CLASSESDIR)vector_p.class \
$(CLASSESDIR)make_vector.class \
$(CLASSESDIR)vector.class \
$(CLASSESDIR)vector_length.class \
$(CLASSESDIR)vector_ref.class \
$(CLASSESDIR)vector_set_b.class \
$(CLASSESDIR)procedure_p.class \
$(CLASSESDIR)apply.class \
$(CLASSESDIR)exit.class \
$(CLASSESDIR)define.class \
$(CLASSESDIR)let.class \
$(CLASSESDIR)letrec.class \
$(CLASSESDIR)begin.class \
$(CLASSESDIR)ifp.class \
$(CLASSESDIR)when.class \
$(CLASSESDIR)unless.class \
$(CLASSESDIR)and.class \
$(CLASSESDIR)or.class \
$(CLASSESDIR)StandardInterpreter.class 

all: $(OBJ)

$(CLASSESDIR)set_b.class: set_b.java
$(CLASSESDIR)not.class: not.java
$(CLASSESDIR)boolean_p.class: boolean_p.java
$(CLASSESDIR)eqv_p.class: eqv_p.java
$(CLASSESDIR)eq_p.class: eq_p.java
$(CLASSESDIR)equal_p.class: equal_p.java
$(CLASSESDIR)pair_p.class: pair_p.java
$(CLASSESDIR)cons.class: cons.java
$(CLASSESDIR)car.class: car.java
$(CLASSESDIR)cdr.class: cdr.java
$(CLASSESDIR)setcar_b.class: setcar_b.java
$(CLASSESDIR)setcdr_b.class: setcdr_b.java
$(CLASSESDIR)caar.class: caar.java
$(CLASSESDIR)cadr.class: cadr.java
$(CLASSESDIR)cdar.class: cdar.java
$(CLASSESDIR)cddr.class: cddr.java
$(CLASSESDIR)caaar.class: caaar.java
$(CLASSESDIR)caadr.class: caadr.java
$(CLASSESDIR)cadar.class: cadar.java
$(CLASSESDIR)caddr.class: caddr.java
$(CLASSESDIR)cdaar.class: cdaar.java
$(CLASSESDIR)cdadr.class: cdadr.java
$(CLASSESDIR)cddar.class: cddar.java
$(CLASSESDIR)cdddr.class: cdddr.java
$(CLASSESDIR)caaaar.class: caaaar.java
$(CLASSESDIR)caaadr.class: caaadr.java
$(CLASSESDIR)caadar.class: caadar.java
$(CLASSESDIR)caaddr.class: caaddr.java
$(CLASSESDIR)cadaar.class: cadaar.java
$(CLASSESDIR)cadadr.class: cadadr.java
$(CLASSESDIR)caddar.class: caddar.java
$(CLASSESDIR)cadddr.class: cadddr.java
$(CLASSESDIR)cdaaar.class: cdaaar.java
$(CLASSESDIR)cdaadr.class: cdaadr.java
$(CLASSESDIR)cdadar.class: cdadar.java
$(CLASSESDIR)cdaddr.class: cdaddr.java
$(CLASSESDIR)cddaar.class: cddaar.java
$(CLASSESDIR)cddadr.class: cddadr.java
$(CLASSESDIR)cdddar.class: cdddar.java
$(CLASSESDIR)cddddr.class: cddddr.java
$(CLASSESDIR)null_p.class: null_p.java
$(CLASSESDIR)list_p.class: list_p.java
$(CLASSESDIR)list.class: list.java
$(CLASSESDIR)length.class: length.java
$(CLASSESDIR)append.class: append.java
$(CLASSESDIR)list_tail.class: list_tail.java
$(CLASSESDIR)list_ref.class: list_ref.java
$(CLASSESDIR)mem.class: mem.java
$(CLASSESDIR)ass.class: ass.java
$(CLASSESDIR)symbol_p.class: symbol_p.java
$(CLASSESDIR)symbol2string.class: symbol2string.java
$(CLASSESDIR)string2symbol.class: string2symbol.java
$(CLASSESDIR)number_p.class: number_p.java
$(CLASSESDIR)real_p.class: real_p.java
$(CLASSESDIR)integer_p.class: integer_p.java
$(CLASSESDIR)zero_p.class: zero_p.java
$(CLASSESDIR)positive_p.class: positive_p.java
$(CLASSESDIR)negative_p.class: negative_p.java
$(CLASSESDIR)equal_oper.class: equal_oper.java
$(CLASSESDIR)less_oper.class: less_oper.java
$(CLASSESDIR)lessequal_oper.class: lessequal_oper.java
$(CLASSESDIR)greater_oper.class: greater_oper.java
$(CLASSESDIR)greaterequal_oper.class: greaterequal_oper.java
$(CLASSESDIR)plus_oper.class: plus_oper.java
$(CLASSESDIR)minus_oper.class: minus_oper.java
$(CLASSESDIR)multiply_oper.class: multiply_oper.java
$(CLASSESDIR)divide_oper.class: divide_oper.java
$(CLASSESDIR)abs.class: abs.java
$(CLASSESDIR)char_p.class: char_p.java
$(CLASSESDIR)char_equal_p.class: char_equal_p.java
$(CLASSESDIR)char_less_p.class: char_less_p.java
$(CLASSESDIR)char_less_equal_p.class: char_less_equal_p.java
$(CLASSESDIR)char_greater_p.class: char_greater_p.java
$(CLASSESDIR)char_greater_equal_p.class: char_greater_equal_p.java
$(CLASSESDIR)string_p.class: string_p.java
$(CLASSESDIR)make_string.class: make_string.java
$(CLASSESDIR)string.class: string.java
$(CLASSESDIR)string_length.class: string_length.java
$(CLASSESDIR)string_ref.class: string_ref.java
$(CLASSESDIR)string_set_b.class: string_set_b.java
$(CLASSESDIR)vector_p.class: vector_p.java
$(CLASSESDIR)make_vector.class: make_vector.java
$(CLASSESDIR)vector.class: vector.java
$(CLASSESDIR)vector_length.class: vector_length.java
$(CLASSESDIR)vector_ref.class: vector_ref.java
$(CLASSESDIR)vector_set_b.class: vector_set_b.java
$(CLASSESDIR)procedure_p.class: procedure_p.java
$(CLASSESDIR)apply.class: apply.java
$(CLASSESDIR)exit.class: exit.java
$(CLASSESDIR)define.class: define.java
$(CLASSESDIR)let.class: let.java
$(CLASSESDIR)letrec.class: letrec.java
$(CLASSESDIR)begin.class: begin.java
$(CLASSESDIR)ifp.class: ifp.java
$(CLASSESDIR)when.class: when.java
$(CLASSESDIR)unless.class: unless.java
$(CLASSESDIR)and.class: and.java
$(CLASSESDIR)or.class: or.java
$(CLASSESDIR)StandardInterpreter.class: StandardInterpreter.java
